Aws/Core.hs
=> Add derived Ord to Method

Aws/S3/Commands/Multipart.hs, Examples/MultipartTransfer.hs, aws.cabal
This is an improved patch as per our discussion.
Let me know if this one is passable. Thanks
=> add ability to modify configuration like CannedAcl for multipart upload

Examples/DynamoDb.hs, aws.cabal
Compiles with ghc 7.10.1 and 7.8.4
=> Fix compile with ghc 7.10.1

Aws/S3/Commands/Multipart.hs, Aws/S3/Commands/PutObject.hs
This is a follow-up of https://github.com/snoyberg/http-client/pull/114 which explains the motivation.
=> Expect: 100-continue support for S3 PutObject and UploadPart commands.

Aws/Iam/Commands.hs, Aws/Iam/Commands/ListMFADevices.hs, Aws/Iam/Commands/ListMfaDevices.hs, Aws/Iam/Core.hs, aws.cabal
Hi,
This implements the IAM ListMFADevices command.
/Fredrik
=> List mfa devices

Aws/S3/Core.hs
OtherStorageClass added to support eg, Google nearline, or whatever other
storage classes AWS or other S3 implementations may add in the future.
S3's new StandardInfrequentAccess class also added, and tested working.
Fixes https://github.com/aristidb/aws/issues/155
=> extend StorageClass to support arbitrary other classes, and add StandardInfrequentAccess

Aws/S3/Commands/Multipart.hs, Examples/MultipartUpload.hs
Hi there,
I wanted a `Sink` for multipart-uploading, so I have implemented that.
Thanks.
=> Add a Sink interface for multipart-uploading

Aws/S3/Commands/PutBucket.hs, Examples/PutBucketNearLine.hs, aws.cabal
This has now been tested working on google cloud storage, and I've also checked that bucket creation on amazon S3 still works.
Closes #182
=> extend PutBucket with pbXStorageClass for google nearline

Aws/S3/Commands/Multipart.hs
Hi there,
I found `chunkedConduit` has a performance issue if `ByteString`s of the input stream are small.
To reproduce, try:
```Haskell
S3.multipartUpload cfg s3cfg mgr (T.pack bucket) (T.pack obj) (CL.replicate 2000000 "0123456789") (chunkSize*1024*1024)
```
I think this PR will fix the issue.
Thanks.
P.S.
I have tried using `ByteString.Builder`, but I have noticed it slightly decreases the performance if the `Source` is `sourceFile`.
=> Improve chunkedConduit performance

Aws/DynamoDb/Core.hs
Adds support for data types which were previously missing:
1. NULL
2. Lists (L)
3. Map (M)
I hit each of these decoding errors while trying to read one of my tables and now I seem to get all of my data!
=> Support the rest of DynamoDB's data types

Aws/Core.hs
Previously the default credentials check would fail with an exception.
It's not uncommon to run in an environment where HOME is unset in
production so this really ought to fail more gracefully.
=> Fail gracefully when HOME is unset

Aws/Core.hs
Allows people to use the temporary tokens as described here:
https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs
=> Use AWS_SESSION_TOKEN if in the environment

Aws/DynamoDb/Core.hs
Allow to parse nested records.
=> Adds `parseAttr` combinator

aws.cabal
It builds fine and seems to work correctly here.
Related: https://github.com/fpco/stackage/issues/1371
=> Allow data-default 0.6

Aws/S3/Core.hs
When you supply one of the `goResponse..` record members in `Aws.S3.Commands.GetObject` with a value which is not already URI encoded then the signature for a pre-signed URL is calculated incorrectly. 
For example signature for an URL constructed as follows is incorrect
```haskell
import qualified Data.Text as T
import qualified Aws.Core as AWS
import qualified Aws.S3 as S3
import Data.Time.Clock (UTCTime)
signUrl :: B8.ByteString -> B8.ByteString -> S3.Bucket -> T.Text -> UTCTime -> IO B8.ByteString
signUrl awsKey awsSecret bucket objectKey expiresAt = do
cred <- AWS.makeCredentials awsKey awsSecret
signature <- AWS.signatureData (AWS.ExpiresAt expiresAt) cred
pure
(AWS.queryToUri
(AWS.signQuery
((S3.getObject bucket objectKey)
{ S3.goResponseExpires = Just . T.pack . show $ expiresAt
} …
```
=> Fix Aws.S3.Commands.GetObject.goResponse.... breaks signed URLs

aws.cabal
Built and tested with xml-conduit 1.4.0.2.
=> Allow xml-conduit 1.4

Aws/Aws.hs
Hi,
Could you support http-proxy?
This PR adds a proxy parameter to Aws.Aws.Configuration.
=> Support for http-proxy

Aws/DynamoDb/Core.hs, Aws/Iam/Core.hs, Aws/S3/Core.hs, Aws/Ses/Core.hs, Aws/SimpleDb/Core.hs, Aws/Sqs/Core.hs, aws.cabal
Add Semigroup instances to compile with ghc 8.4:
https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid#Writingcompatiblecode
=> Fix build with ghc 8.4

Aws/Aws.hs, Aws/Core.hs, Aws/DynamoDb/Core.hs, Aws/S3/Commands/GetObject.hs, Aws/S3/Core.hs, Aws/Sqs/Core.hs, Examples/DynamoDb.hs, Examples/GetObject.hs, Examples/GetObjectGoogle.hs, Examples/GetObjectV4.hs, Examples/MultipartTransfer.hs, Examples/NukeBucket.hs, Examples/PutBucketNearLine.hs, Examples/PutObjectIA.hs, README.md, aws.cabal, stack.yaml, tests/S3/Main.hs
If someone can run the test suite on this, I'd consider it good to go.
=> update to conduit-1.3 and http-conduit-2.3

Aws/S3/Commands.hs, Aws/S3/Commands/PutBucketVersioning.hs, aws.cabal
closes https://github.com/aristidb/aws/issues/254
=> add Aws.S3.Commands.PutBucketVersioning

Aws/S3/Commands/PutObject.hs
closes https://github.com/aristidb/aws/issues/258
Straightforward enough, cut-n-paste from Aws.S3.Commands.Multipart.
I've tested this and it works.
=> add etag to PutObjectResponse (#258)

Aws/DynamoDb/Commands/Table.hs, Aws/DynamoDb/Commands/UpdateItem.hs, Aws/DynamoDb/Core.hs, aws.cabal
Closes https://github.com/aristidb/aws/issues/275
Aeson 2 fixes a potential DOS attack. So, I recommend treating this as a moderate ugency fix.
=> build with aeson 2

Aws/Aws.hs, Aws/Core.hs, Aws/S3/Commands/Multipart.hs, Aws/S3/Core.hs, Examples/DynamoDb.hs, Examples/MultipartUpload.hs, Examples/NukeBucket.hs, aws.cabal, tests/DynamoDb/Main.hs, tests/S3/Main.hs, tests/Sqs/Main.hs, tests/Utils.hs
This fixes all build warnings.
=> Warnings removal

Aws/S3/Core.hs, CHANGELOG.md, aws.cabal
Closes https://github.com/aristidb/aws/issues/283
=> support custom S3 regions

Aws/S3/Commands.hs, Aws/S3/Commands/GetBucketVersioning.hs, aws.cabal
closes https://github.com/aristidb/aws/issues/290
=> add Aws.S3.Commands.GetBucketVersioning (#255)

Aws/S3/Core.hs
Implemented in s3SignQuery since that is a lower-impact change than modifying each signQuery instance.
closes https://github.com/aristidb/aws/issues/286
=> add s3UserAgent
